allowBuilds:
  cbor-extract: false
  '@automerge/automerge-repo@git+https://github.com/automerge/automerge-repo.git': true
  esbuild: true
overrides:
  "@automerge/automerge": 3.3.2
  "@automerge/automerge-subduction": 0.16.1
