mod coln-compiler-wasm '../packages/coln-compiler-wasm'

build_dir := "../_build/web/compiler"
lab_app_dir := "lab"

stage-web-lab:
    #!/usr/bin/env bash
    set -euxo pipefail
    if [[ ! -f "{{ build_dir }}/dist/coln.wasm" || ! -f "{{ build_dir }}/dist/ghc_wasm_jsffi.js" || ! -f "{{ build_dir }}/dist/loadHaskellWasm.js" ]]; then
      just coln-compiler-wasm::build
    fi
    mkdir -p "{{ lab_app_dir }}/public/dist"
    cp "{{ build_dir }}/dist/coln.wasm" "{{ lab_app_dir }}/public/dist/coln.wasm"
    cp "{{ build_dir }}/dist/ghc_wasm_jsffi.js" "{{ lab_app_dir }}/public/dist/ghc_wasm_jsffi.js"
    cp "{{ build_dir }}/dist/loadHaskellWasm.js" "{{ lab_app_dir }}/public/dist/loadHaskellWasm.js"

build-web-lab: stage-web-lab
    pnpm --dir {{ lab_app_dir }} build

dev-web-lab: stage-web-lab
    pnpm --dir {{ lab_app_dir }} dev
